### PR TITLE
added support for gridView & exporting index

### LINKED ISSUE #5: Pagination for grid view
Adding support for pagination for all list related views. For example GridView

### PR DESCRIPTION
**Pull request by Saifallak**
added support for gridView through enum

fixes #5

also exporting index to people so they can use it to customize the item builder.

### CODE REVIEW

**Comment by Saifallak** [comment]
this is ready for review, if you have some time @excogitatr

**Comment by vedartm** [comment]
Everything works man. Great work @Saifallak 🎉

**Comment by vedartm** [comment]
@all-contributors please add @Saifallak

**Comment by vedartm** [comment]
@all-contributors please add @Saifallak for code

**Comment by Saifallak** [comment]
Thanks @excogitatr

**Pull request merged**
