### PR TITLE
Add refresh

### PR DESCRIPTION
**Pull request by jezsung**
I made a refresh feature. You can refresh the page by referring to the PaginationViewState using a global key and can call key.currentState.refresh().

### CODE REVIEW

**Comment by vedartm** [comment]
Great work @jezsung. But what if we can make it more simple by adding `RefreshIndicator` widget inside the `PaginationView` widget and add `onRefresh` in the PaginationView widget.

In the implementation part, if onRefresh is not null we can wrap it with RefreshIndicator and if it is null then we can simply follow that normal flow. The result will look something like this,

```dart
       PaginationView<User>(
          paginationViewType: paginationViewType,
          onRefresh: () async {  ...  } // some callback function during refresh 
          itemBuilder: (context, user, index) => ListTile(
            title: Text(user.name),
            subtitle: Text(user.email),
            leading: CircleAvatar(
              child: Icon(Icons.person),
            ),
          )
        )
```

In this case, users don't have to wrap it in the `RefreshIndicator` because we did the implementation under the hood.
What do you think about it?

**Comment by jezsung** [comment]
@excogitatr  Good idea! But I think it also has to offer flexibility because someone might need to refresh by clicking on a button or some custom event.
What about keeping this feature and add `pullToRefresh` parameter for easy use?

**Comment by vedartm** [comment]
Interesting! That should work @jezsung

**Comment by jezsung** [comment]
@excogitatr I'm gonna make it now give me few minutes

**Comment by jezsung** [comment]
@excogitatr I've done it! Please check it out. And I found a problem that listview got back to the previous offset when refreshing by clicking on the button on the app bar. I solved it by passing the scroll controller to the event as a parameter which's not that cool but it works well.

**Comment by excogitatr** [comment]
@all-contributors please add @Saifallak for code

**Comment by vedartm** [comment]
@all-contributors please add @jezsung for code

**Pull request merged**
